# locations:
master_file: '/PETRA/SED/BEATS/IH/scratch/master.csv'
master_url: ''
experiment_dir: "/PETRA/SED/BEATS/IH/"
experiment_name: ''
dataset: ''
recon_dir: '/PETRA/SED/BEATS/IH/scratch/pippo/recon'
cor_dir: '/PETRA/SED/BEATS/IH/scratch/pippo/cor'
imagej_launcher: '/opt/fiji-linux64/Fiji.app/ImageJ-linux64'
# general settings
ncore: 4
normalize_on_load: True
sino_range: [980, 1020]
proj_range: [0, 4001]
averaging: 'mean'
# Center Of Rotation settings
COR: 1280
COR_step: 1
COR_auto: False
COR_algorithm: 'TomoPy'
# Phase retrieval settings
phase_object: False
pixelsize: 6.5
energy: 20.
sdd: 20.
alpha: 0.002
# Reconstruction settings
# algorithms: [ "gridrec", "fbp_cuda_astra", "sirt_cuda_astra", "sart_cuda_astra", "cgls_cuda_astra" ]
algorithm: 'gridrec'
num_iter: 50
# Output settings
uintconvert: False
bitdepth: 'uint8'
circmask: False
circmask_ratio: 0.9
# Plot settings
plotreconhist: False
hist_speed: 'fast'