# App settings:
master_file: '/PETRA/SED/BEATS/IH/scratch/master.csv'
master_spreadsheet: 'master'
gspread_key: ''
experiment_dir: "/PETRA/SED/BEATS/IH/"
experiment_name: '<experiment_name>'
h5file: ''
dataset: '<dataset>'
recon_dir: '/PETRA/SED/BEATS/IH/scratch/pippo/recon'
cor_dir: '/PETRA/SED/BEATS/IH/scratch/pippo/cor'
auto_complete: True
imagej_launcher: '/opt/fiji-linux64/Fiji.app/ImageJ-linux64'
# General settings
expert: False
ncore: 4
normalize_on_load: True
recon_sino_range: False
sino_range: [980, 1020]
recon_proj_range: False
proj_range: [0, 4001]
averaging: 'mean'
# Stripe removal settings
stripe_remove: False
stripe_removal_method: 'remove_all_stripe'
snr: 3.
sigma: 3.
size: 51
norm: True
la_size: 61
sm_size: 21
dim: 1
drop_ratio: 0.1
# Center Of Rotation settings
COR: 1280
COR_step: 1
COR_auto: False
COR_algorithm: 'TomoPy'
# Phase retrieval settings
phase_object: False
pad: True
pixelsize: 6.5
energy: 20.
sdd: 20.
alpha: 0.002
# Reconstruction settings
# algorithms: [ "gridrec", "fbp_cuda_astra", "sirt_cuda_astra", "sart_cuda_astra", "cgls_cuda_astra" ]
algorithm: 'gridrec'
num_iter: 50
# Output settings
uintconvert: False
bitdepth: 'uint8'
circmask: False
circmask_ratio: 0.9
writemidplanes: True
# Plot settings
plotreconhist: False
hist_speed: 'fast'